### PR TITLE
Revised Tourniquet Instructions

### PR DESCRIPTION
**Pull request by jenwilsonglia**
PDF revised instructions have been added as a link in the readme file.

### CODE REVIEW

**Comment by tareko** [comment]
A few points and questions:

1. Why don't the revised instructions _replace_ the current english instructions? It seems to me that a strength of the version control system is that we never had to do "instructions_revised", but rather just one set of the most current english language instructions.
2. Why are the instructions in PDF as opposed to MD?
3. Does the addendum truly have to be a separate file? Why not notes at the bottom of the original?
4. Files in assets_instructions (i.e., the JPG and the SVG) should be named appropriately. For example, figureX.jpg or partX.jpg. I know these names are only minimally instructive, but currently the name of the JPG appears to be a dated / serialized name and the other one doesn't really fit.

My proposal, @jenwilsonglia, is to spend an hour together and make these small modifications to get it up! You've done a lot of work, and only a little bit more is required to get this fully ready!

tarek : )

**Comment by jenwilsonglia** [comment]
I totally agree! I would love to get everything up properly named and the instructions in Markdown to replace the English instructions.   
  

  
This was what I could do to get the new instructions up asap, but your input is really welcome and please let's spend the time to get it right!
  

  
-Jen
  

  

  

  
  
  
  
>

**Comment by jenwilsonglia** [comment]
Hi Tarek,

I have revised the instructions to replace the english instructions. They're in MD. The addendum is at the bottom of the instructions. I have removed those two photos from the assets_instructions folder and have added all the photos needed and properly named.

I'm working on the FAQ page now. I will create a pull request once I'm done.

Thanks for your help with this!

-Jen

August 16, 2022 9:14 PM, "Tarek Loubani" ***@***.*** ***@***.******@***.***>)> wrote:
	A few points and questions:
	* Why don't the revised instructions replace the current english instructions? It seems to me that a strength of the version control system is that we never had to do "instructions_revised", but rather just one set of the most current english language instructions.
	* Why are the instructions in PDF as opposed to MD?
	* Does the addendum truly have to be a separate file? Why not notes at the bottom of the original?
	* Files in assets_instructions (i.e., the JPG and the SVG) should be named appropriately. For example, figureX.jpg or partX.jpg. I know these names are only minimally instructive, but currently the name of the JPG appears to be a dated / serialized name and the other one doesn't really fit.
	My proposal, @jenwilsonglia (https://github.com/jenwilsonglia), is to spend an hour together and make these small modifications to get it up! You've done a lot of work, and only a little bit more is required to get this fully ready!

	tarek : )

**Review by tareko — COMMENTED** [review]
This appears to be a duplicate of a more recent pull request, which was merged.

**Pull request closed without merging**
